# Generated by Django 5.0.3 on 2024-03-30 06:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='members',
            field=models.ManyToManyField(related_name='joined_leagues', to=settings.AUTH_USER_MODEL),
        ),
    ]
