# Generated by Django 5.0.3 on 2024-03-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_top_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_elo',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='top_teams',
            field=models.JSONField(default={'A Town Show Down': ['Team 1', 'Team 2', 'Team 3'], 'Legends': ['Team 1', 'Team 2', 'Team 3'], 'Tufaan': ['Team 1', 'Team 2', 'Team 3'], 'Udaan': ['Team 1', 'Team 2', 'Team 3']}),
        ),
    ]
