# Generated by Django 5.0.3 on 2024-03-30 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_user_elo_alter_userprofile_top_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='top_teams',
            field=models.JSONField(default={'A Town Show Down': ['', '', ''], 'Bollywood Berkley': ['', '', ''], 'Jazba': ['', '', ''], 'Legends': ['', '', ''], 'Magic City Maza': ['', '', ''], 'Nasha': ['', '', ''], 'Tufaan': ['', '', ''], 'Udaan': ['', '', '']}),
        ),
    ]
