# Generated by Django 5.0.3 on 2024-03-27 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comps', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_first_place', models.CharField(blank=True, max_length=100, null=True)),
                ('actual_second_place', models.CharField(blank=True, max_length=100, null=True)),
                ('actual_third_place', models.CharField(blank=True, max_length=100, null=True)),
                ('comp_name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='comps.comp')),
            ],
        ),
    ]
